### ISSUE TITLE
Update on HyperFields

### ISSUE THREAD

**Issue by sudarshan1994** [StellarCheng/Awesome-Text-to-3D#3]
Thank you for your effort in building this repo of papers! If you have time please update HyperFields as it got accepted to [ICML](https://icml.cc/virtual/2024/poster/34847).

**Comment by StellarCheng** [comment]
> Thank you for your effort in building this repo of papers! If you have time please update HyperFields as it got accepted to [ICML](https://icml.cc/virtual/2024/poster/34847).

Thank you for your kind words!

I am pleased to update you that HyperFields has been accepted to ICML. I will update the repository accordingly.

**Comment by sudarshan1994** [comment]
thank you!
